version: '3'

services:
    phpfpm:
        image: php_benchmark
        ports:
            - "8080:8080"
        command: php-fpm -F -R
    nginx:
        image: nginx:1.13.3-alpine
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
        link:
            - phpfpm
